### ISSUE TITLE
NameError: name 'BeautifulSoup' is not defined

### ISSUE THREAD

**Issue by Math170** [codewithvincent1/tiktokVideoScraper#5]
```
STEP 3: Time to download 177 videos
Downloading video: 0
Downloading video 0 from: https://www.tiktok.com/
STEP 4: Getting the download link
If this step fails, PLEASE read the steps above
Traceback (most recent call last):
  File "c:\Users\doria\OneDrive\Bureau\auto-tiktok\auto.py", line 108, in <module>
    downloadVideo(url, index)
  File "c:\Users\doria\OneDrive\Bureau\auto-tiktok\auto.py", line 52, in downloadVideo
    downloadSoup = BeautifulSoup(response.text, "html.parser")
                   ^^^^^^^^^^^^^
NameError: name 'BeautifulSoup' is not defined``
```

i have this in the terminal, how can i fix it please ?

**Comment by wealthypotato** [comment]
any luck?

**Comment by rayyanshikoh** [comment]
At the top of auto.py, type:
```
import requests
from bs4 import BeautifulSoup
```
