### ISSUE TITLE
javascript error: document.getElementsByClassName(...).forEach is not a function

### ISSUE THREAD

**Issue by przanowo** [codewithvincent1/tiktokVideoScraper#6]
The script was working for me weeks ago, but now getting the following error:

STEP 1: Open Chrome browser

DevTools listening on ws://127.0.0.1:52364/devtools/browser/4ce50f56-8f18-454a-80e0-2031e7426bec
[44136:53068:0520/005754.306:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[44136:53068:0520/005754.795:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
STEP 2: Scrolling page
Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "E:\AI PIMP\Scraper\scrape_video.py", line 115, in <module>
    urlsToDownload = driver.execute_script(script)
  File "C:\Users\Oskar\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Oskar\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Oskar\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: document.getElementsByClassName(...).forEach is not a function
  (Session info: chrome=125.0.6422.61)
Stacktrace:
        GetHandleVerifier [0x00007FF6265A22C2+60002]
        (No symbol) [0x00007FF62651CA59]
        (No symbol) [0x00007FF6263D7EDA]
        (No symbol) [0x00007FF6263DDD0E]
        (No symbol) [0x00007FF6263E0988]
        (No symbol) [0x00007FF62646C9CB]
        (No symbol) [0x00007FF62644C28A]
        (No symbol) [0x00007FF62646BCC7]
        (No symbol) [0x00007FF62644C033]
        (No symbol) [0x00007FF626419657]
        (No symbol) [0x00007FF62641A251]
        GetHandleVerifier [0x00007FF6268B3E2D+3278285]
        GetHandleVerifier [0x00007FF626900190+3590448]
        GetHandleVerifier [0x00007FF6268F61D0+3549552]
        GetHandleVerifier [0x00007FF626651DE6+779654]
        (No symbol) [0x00007FF626527ACF]
        (No symbol) [0x00007FF626522EE4]
        (No symbol) [0x00007FF626523072]
        (No symbol) [0x00007FF626512C4F]
        BaseThreadInitThunk [0x00007FFA68D7257D+29]
        RtlUserThreadStart [0x00007FFA6A22AA48+40]

**Comment by przanowo** [comment]
SOLVED:

# this class may change, so make sure to inspect the page and find the correct class
className = " css-1as5cen-DivWrapper e1cg0wnj1"

script  = "let l = [];"
script += "Array.from(document.getElementsByClassName(\""
script += className
script += "\")).forEach(item => { l.push(item.querySelector('a').href)});"
script += "console.log(l);"
script += "return l;"

urlsToDownload = driver.execute_script(script)

# Print the array of links to debug
print(f"Links found: {urlsToDownload}")
